package estrcCondicionales;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Yber-M
 */
public class frmAlumno extends javax.swing.JFrame {
    Alumno alum;
    /**
     * Creates new form frmAlumno
     */
    public frmAlumno() {
        initComponents();
        this.setLocationRelativeTo(this);
        
        SetImageLabel(jlbImgSalir, "F:\\2do Ciclo\\MP_Sesión03\\src\\iconos\\exit_icon-icons.com_70975.png");
        SetImageLabel(jlbImgCalcular, "F:\\2do Ciclo\\MP_Sesión03\\src\\iconos\\1904677-add-addition-calculate-charge-create-new-plus_122527.png");
        SetImageLabel(jlbImgLimpiar, "F:\\2do Ciclo\\MP_Sesión03\\src\\iconos\\biggarbagebin_121980.png");
    }
    String Verif () {
        if (jtxtNombre.getText().equals("")) return "Apellidos y Nombres";
        if (jtxtCodeAlum.getText().equals("")) return "código";
        if (jtxtNota1.getText().equals("") || Double.parseDouble(jtxtNota1.getText())< 0 || 
                Double.parseDouble(jtxtNota1.getText()) > 20) return "Nota 1";
        if (jtxtNota2.getText().equals("") || Double.parseDouble(jtxtNota2.getText())< 0 || 
                Double.parseDouble(jtxtNota2.getText()) > 20) return "Nota 2";
        if (jtxtNota3.getText().equals("") || Double.parseDouble(jtxtNota3.getText())< 0 || 
                Double.parseDouble(jtxtNota3.getText()) > 20) return "Nota 3";
        return Verif();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jtxtNombre = new javax.swing.JTextField();
        jtxtCodeAlum = new javax.swing.JTextField();
        jtxtNota2 = new javax.swing.JTextField();
        jtxtNota1 = new javax.swing.JTextField();
        jtxtNota3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxaMostrar = new javax.swing.JTextArea();
        jcbxCursos = new javax.swing.JComboBox<>();
        jbtnCalcular = new javax.swing.JButton();
        jlbImgCalcular = new javax.swing.JLabel();
        jbtnSalir = new javax.swing.JButton();
        jbtnLimp = new javax.swing.JButton();
        jlbImgLimpiar = new javax.swing.JLabel();
        jlbImgSalir = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtNombre.setFont(new java.awt.Font("mononoki", 1, 14)); // NOI18N
        jtxtNombre.setForeground(new java.awt.Color(51, 51, 255));
        jtxtNombre.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre y Apellidos"));
        jtxtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNombreActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 30, 274, 62));

        jtxtCodeAlum.setFont(new java.awt.Font("mononoki", 1, 14)); // NOI18N
        jtxtCodeAlum.setForeground(new java.awt.Color(0, 204, 204));
        jtxtCodeAlum.setBorder(javax.swing.BorderFactory.createTitledBorder("Código"));
        jPanel2.add(jtxtCodeAlum, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 30, 145, 62));

        jtxtNota2.setFont(new java.awt.Font("mononoki", 1, 14)); // NOI18N
        jtxtNota2.setForeground(new java.awt.Color(0, 153, 0));
        jtxtNota2.setBorder(javax.swing.BorderFactory.createTitledBorder("Nota 2"));
        jPanel2.add(jtxtNota2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 73, 58));

        jtxtNota1.setFont(new java.awt.Font("mononoki", 1, 14)); // NOI18N
        jtxtNota1.setForeground(new java.awt.Color(0, 153, 0));
        jtxtNota1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nota 1"));
        jPanel2.add(jtxtNota1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 73, 58));

        jtxtNota3.setFont(new java.awt.Font("mononoki", 1, 14)); // NOI18N
        jtxtNota3.setForeground(new java.awt.Color(0, 153, 0));
        jtxtNota3.setBorder(javax.swing.BorderFactory.createTitledBorder("Nota 3"));
        jPanel2.add(jtxtNota3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 73, 58));

        jtxaMostrar.setBackground(new java.awt.Color(102, 102, 102));
        jtxaMostrar.setColumns(20);
        jtxaMostrar.setFont(new java.awt.Font("mononoki", 3, 14)); // NOI18N
        jtxaMostrar.setForeground(new java.awt.Color(51, 255, 0));
        jtxaMostrar.setRows(5);
        jScrollPane1.setViewportView(jtxaMostrar);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 257, 540, 167));

        jcbxCursos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "METODOLOGÍA DE LA PROGRAMACIÓN", "MATEMÁTICA 2", "SISTÉMICA" }));
        jcbxCursos.setBorder(javax.swing.BorderFactory.createTitledBorder("Asignaturas"));
        jPanel2.add(jcbxCursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, 60));

        jbtnCalcular.setBackground(new java.awt.Color(0, 102, 204));
        jbtnCalcular.setFont(new java.awt.Font("mononoki", 1, 14)); // NOI18N
        jbtnCalcular.setForeground(new java.awt.Color(255, 255, 255));
        jbtnCalcular.setText("CALCULAR");
        jbtnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCalcularActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 460, 111, 33));
        jPanel2.add(jlbImgCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 30, 30));

        jbtnSalir.setBackground(new java.awt.Color(255, 0, 0));
        jbtnSalir.setFont(new java.awt.Font("mononoki", 1, 14)); // NOI18N
        jbtnSalir.setForeground(new java.awt.Color(255, 255, 255));
        jbtnSalir.setText("SALIR");
        jbtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSalirActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 460, 111, 33));

        jbtnLimp.setBackground(new java.awt.Color(204, 0, 204));
        jbtnLimp.setFont(new java.awt.Font("mononoki", 1, 14)); // NOI18N
        jbtnLimp.setForeground(new java.awt.Color(255, 255, 255));
        jbtnLimp.setText("LIMPIAR");
        jbtnLimp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLimpActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnLimp, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 111, 33));
        jPanel2.add(jlbImgLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 30, 30));
        jPanel2.add(jlbImgSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, 30, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jbtnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCalcularActionPerformed
        // Marlon Yber Quispe Olano
        // Yb.M;
        
        String nom = jtxtNombre.getText(); 
        String code = jtxtCodeAlum.getText();
        double not1 = Double.parseDouble(jtxtNota1.getText());
        double not2 = Double.parseDouble(jtxtNota2.getText());
        double not3 = Double.parseDouble(jtxtNota3.getText());
        String course = jcbxCursos.getSelectedItem().toString();
        
        
        alum = new Alumno (nom, code, not1, not2, not3, course);
        jtxaMostrar.append("Código      : " + alum.cod + "\n");
        jtxaMostrar.append("Nombre      : " + alum.nombre + "\n");
        jtxaMostrar.append("Asignatura  : " + alum.asignatura + "\n");
        jtxaMostrar.append("Nota 1      : " + alum.getNot1() + "\n");
        jtxaMostrar.append("Nota 2      : " + alum.getNot2() + "\n");
        jtxaMostrar.append("Nota 3      : " + alum.getNot3() + "\n");
        jtxaMostrar.append("Promedio    : " + alum.promedio() +  "\n");
    }//GEN-LAST:event_jbtnCalcularActionPerformed

    private void jbtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jbtnSalirActionPerformed

    private void jbtnLimpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLimpActionPerformed
        // Marlon Yber Quispe Olano - Yb.M;
        jtxtCodeAlum.setText("");
        jtxtNombre.setText("");
        jtxtNota1.setText("");
        jtxtNota2.setText("");
        jtxtNota3.setText("");
        jtxaMostrar.setText("");
    }//GEN-LAST:event_jbtnLimpActionPerformed

    private void jtxtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAlumno().setVisible(true);
            }
        });
        
    }
    
    private void SetImageLabel(JLabel labelname, String root) {
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(labelname.getWidth(), labelname.getHeight(), Image.SCALE_DEFAULT));
        labelname.setIcon(icon);
        this.repaint();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnCalcular;
    private javax.swing.JButton jbtnLimp;
    private javax.swing.JButton jbtnSalir;
    private javax.swing.JComboBox<String> jcbxCursos;
    private javax.swing.JLabel jlbImgCalcular;
    private javax.swing.JLabel jlbImgLimpiar;
    private javax.swing.JLabel jlbImgSalir;
    private javax.swing.JTextArea jtxaMostrar;
    private javax.swing.JTextField jtxtCodeAlum;
    private javax.swing.JTextField jtxtNombre;
    private javax.swing.JTextField jtxtNota1;
    private javax.swing.JTextField jtxtNota2;
    private javax.swing.JTextField jtxtNota3;
    // End of variables declaration//GEN-END:variables
    

}

