package Sesion14_txt;

import java.text.DecimalFormat;
import javax.swing.table.DefaultTableModel;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.text.DecimalFormat;
import java.util.StringTokenizer;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

public class frmEmpleados extends javax.swing.JFrame {

    DefaultTableModel ModeloTabla;

    Empleados UnEmp;
    Empleados[] ArregloEmp;

    String[] cabecera = {"N", "Codigo", "Nombres", "Area", "Tipo Seg", "Horas Extras",
        "Sueldo", "Monto H.E", "Monto Seguro", "Monto Essalud", "Sueldo Neto"};

    String[][] data = {};
    int NumEmp;

    public frmEmpleados() {
        initComponents();

        ArregloEmp = new Empleados[100];
        ModeloTabla = new DefaultTableModel(data, cabecera);
        jtblDatos.setModel(ModeloTabla);

        CambiarTamañoColumnas();

        NumEmp = 0;

        ExtraerDeArchivo();
    }

    void CambiarTamañoColumnas() {
        TableColumn column = null;

        column = jtblDatos.getColumnModel().getColumn(0);
        column.setPreferredWidth(30);
        column = jtblDatos.getColumnModel().getColumn(1);
        column.setPreferredWidth(60);
        column = jtblDatos.getColumnModel().getColumn(2);
        column.setPreferredWidth(180);
        column = jtblDatos.getColumnModel().getColumn(3);
        column.setPreferredWidth(100);

    }

    void ExtraerDeArchivo() {
        String linea;
        try {
            FileReader fr = new FileReader("empleados.txt");
            BufferedReader br = new BufferedReader(fr);
            while ((linea = br.readLine()) != null) {
                StringTokenizer st = new StringTokenizer(linea, "|");
                String cod = st.nextToken();
                String nom = st.nextToken();
                String area = st.nextToken();
                double sueldo = Double.parseDouble(st.nextToken());
                int h_extras = Integer.parseInt(st.nextToken());
                String seguro = st.nextToken();

                UnEmp = new Empleados(cod, nom, area, sueldo, h_extras, seguro);
                ArregloEmp[NumEmp] = UnEmp;
                InsertarEnTabla(UnEmp);
                NumEmp++;
            }
            br.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error en la lectura"
                    + " del archivo ..." + ex);
        }
    }

    void GrabarEnArchivo(Empleados e) {

        try {
            FileWriter fw = new FileWriter("empleados.txt", true);
            PrintWriter pw = new PrintWriter(fw);
            pw.println(e.codigo + "|" + e.nombre + "|" + e.area + "|" + e.sueldobase + "|" + e.horasExtras + "|" + e.tipoSeg);
            pw.close();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error en la grabacion....." + ex);
        }

    }

    void InsertarEnTabla(Empleados UnEmp) {

        DecimalFormat df2 = new DecimalFormat("####.00");

        String me = df2.format(UnEmp.montoHExtras());
        String ms = df2.format(UnEmp.montoSeguro());
        String mes = df2.format(UnEmp.montoEssalud());
        String SN = df2.format(UnEmp.sueldoNeto());

        Object[] fila = {NumEmp + 1, UnEmp.codigo, UnEmp.nombre, UnEmp.area, UnEmp.tipoSeg,
            UnEmp.horasExtras, UnEmp.sueldobase, me, ms, mes, SN};

        ModeloTabla.addRow(fila);
    }

    void LimpiarEntradas() {
        jtxtCodigo.setText("");
        jtxtNombre.setText("");
        jcbxSeguro.setSelectedIndex(0);
        jtxtSueldoBase.setText("");
        jtxtHorasExtras.setText("");
        jcbxArea.setSelectedIndex(0);
        jtxtCodigo.requestFocus();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxtCodigo = new javax.swing.JTextField();
        jtxtSueldoBase = new javax.swing.JTextField();
        jtxtNombre = new javax.swing.JTextField();
        jtxtHorasExtras = new javax.swing.JTextField();
        jcbxSeguro = new javax.swing.JComboBox<>();
        jbtnMostrar = new javax.swing.JButton();
        jbtnGrabar = new javax.swing.JButton();
        jbtnLimpiar = new javax.swing.JButton();
        jbtnSalir = new javax.swing.JButton();
        jcbxArea = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblDatos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jtxtb = new javax.swing.JTextField();
        jtxtc = new javax.swing.JTextField();
        jtxtd = new javax.swing.JTextField();
        jtxte = new javax.swing.JTextField();
        jtxtf = new javax.swing.JTextField();
        jtxta = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtCodigo.setBorder(javax.swing.BorderFactory.createTitledBorder("Codigo"));
        getContentPane().add(jtxtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 20, 160, 60));

        jtxtSueldoBase.setBorder(javax.swing.BorderFactory.createTitledBorder("Sueldo Base"));
        getContentPane().add(jtxtSueldoBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 85, 170, 60));

        jtxtNombre.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre"));
        getContentPane().add(jtxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 280, 60));

        jtxtHorasExtras.setBorder(javax.swing.BorderFactory.createTitledBorder("Horas Extras"));
        getContentPane().add(jtxtHorasExtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 250, 60));

        jcbxSeguro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONE", "AFP", "SNP" }));
        jcbxSeguro.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de Seguro"));
        getContentPane().add(jcbxSeguro, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 170, 60));

        jbtnMostrar.setText("MOSTRAR RESUMEN");
        jbtnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMostrarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 60, 150, 60));

        jbtnGrabar.setText("GRABAR");
        jbtnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGrabarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnGrabar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 150, 60));

        jbtnLimpiar.setText("LIMPIAR");
        jbtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, 150, 60));

        jbtnSalir.setText("SALIR");
        jbtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 60, 150, 60));

        jcbxArea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONE", "SISTEMAS", "ADMINISTRACION", "MARKETING" }));
        jcbxArea.setBorder(javax.swing.BorderFactory.createTitledBorder("Area Laboral"));
        getContentPane().add(jcbxArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 190, 60));

        jtblDatos.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jtblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N", "Codigo", "Nombre", "Area", "Tipo Seg", "Horas Extra", "Sueldo", "Monto H.E", "Monto Seguro", "Monto Essalud", "Sueldo Neto"
            }
        ));
        jScrollPane1.setViewportView(jtblDatos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 950, 200));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Resumen de datos"));

        jtxtb.setBorder(javax.swing.BorderFactory.createTitledBorder(" Promedio de suelo netos en el area de Marketing"));

        jtxtc.setBorder(javax.swing.BorderFactory.createTitledBorder("N de emp. cuyo monto de seguro es > 100"));

        jtxtd.setBorder(javax.swing.BorderFactory.createTitledBorder("N. de Emp. de sistemas con montoHE entre 500 y 800"));

        jtxte.setBorder(javax.swing.BorderFactory.createTitledBorder("Empleado del SNP con el menor monto de descuento"));

        jtxtf.setBorder(javax.swing.BorderFactory.createTitledBorder("Total que gasta la empresa en pagar a todos sus Empleados"));

        jtxta.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre del empleado con mas sueldo"));
        jtxta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtxtd, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxte, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtxta, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtb, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtc)
                    .addComponent(jtxtf, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE))
                .addGap(6, 6, 6))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtb, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtc, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxta, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtd, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxte, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtf, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 950, 210));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGrabarActionPerformed

        String cod = jtxtCodigo.getText();
        String nom = jtxtNombre.getText();
        String seguro = jcbxSeguro.getSelectedItem().toString();
        double sueldo = Double.parseDouble(jtxtSueldoBase.getText());
        int h_extras = Integer.parseInt(jtxtHorasExtras.getText());
        String area = jcbxArea.getSelectedItem().toString();

        UnEmp = new Empleados(cod, nom, area, sueldo, h_extras, seguro);

        ArregloEmp[NumEmp] = UnEmp;

        InsertarEnTabla(UnEmp);

        NumEmp++;

        LimpiarEntradas();

    }//GEN-LAST:event_jbtnGrabarActionPerformed

    private void jbtnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMostrarActionPerformed

        String a = "", e = "";
        double b = 0, c = 0, ss = 0, cont = 0, d = 0, f = 0, mayor = -1, menor = 999999;

        for (int i = 0; i < NumEmp; i++) {

            if (ArregloEmp[i].sueldoNeto() > mayor) {
                mayor = ArregloEmp[i].sueldoNeto();
                a = ArregloEmp[i].nombre;
            }

            if (ArregloEmp[i].area.equals("Marketing")) {
                ss = ss + ArregloEmp[i].sueldoNeto();
                cont++;
                b = ss / cont;
            }

            if (ArregloEmp[i].montoSeguro() > 100) {
                c++;
            }

            if (ArregloEmp[i].area.equals("Sistemas") && ArregloEmp[i].montoHExtras() >= 500
                    && ArregloEmp[i].montoHExtras() <= 800) {
                d++;
            }

            if (ArregloEmp[i].tipoSeg.equals("SNP") && ArregloEmp[i].montoDescuento() < menor) {
                menor = ArregloEmp[i].montoDescuento();
                e = ArregloEmp[i].nombre;
            }

            f = f + ArregloEmp[i].sueldoBruto();

            //datosdesalida
            jtxta.setText(a);
            jtxtb.setText(String.valueOf(b));
            jtxtc.setText(String.valueOf(c));
            jtxtd.setText(String.valueOf(d));
            jtxte.setText(e);
            jtxtf.setText(String.valueOf(f));
        }
    }//GEN-LAST:event_jbtnMostrarActionPerformed

    private void jbtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLimpiarActionPerformed
        LimpiarEntradas();
    }//GEN-LAST:event_jbtnLimpiarActionPerformed

    private void jbtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jbtnSalirActionPerformed

    private void jtxtaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEmpleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnGrabar;
    private javax.swing.JButton jbtnLimpiar;
    private javax.swing.JButton jbtnMostrar;
    private javax.swing.JButton jbtnSalir;
    private javax.swing.JComboBox<String> jcbxArea;
    private javax.swing.JComboBox<String> jcbxSeguro;
    private javax.swing.JTable jtblDatos;
    private javax.swing.JTextField jtxtCodigo;
    private javax.swing.JTextField jtxtHorasExtras;
    private javax.swing.JTextField jtxtNombre;
    private javax.swing.JTextField jtxtSueldoBase;
    private javax.swing.JTextField jtxta;
    private javax.swing.JTextField jtxtb;
    private javax.swing.JTextField jtxtc;
    private javax.swing.JTextField jtxtd;
    private javax.swing.JTextField jtxte;
    private javax.swing.JTextField jtxtf;
    // End of variables declaration//GEN-END:variables
}
